"""
Script to create sample furniture objects for the kitchen designer.
Run with: python manage.py shell < create_sample_furniture.py
"""

from kitchen.models import FurnitureObject, DesignerSettings
from decimal import Decimal

# Clear existing sample data
print("Clearing existing sample data...")
FurnitureObject.objects.all().delete()
DesignerSettings.objects.filter(user=None).delete()

# Create furniture objects
furniture_data = [
    {
        "name": "Base Cabinet 60cm",
        "description": "Standard base cabinet for kitchen countertops",
        "object_type": "base_cabinet",
        "glb_file": "furniture_objects/base_cabinet_60.glb",
        "default_width": Decimal("0.60"),
        "default_height": Decimal("0.85"),
        "default_depth": Decimal("0.60"),
        "min_width": Decimal("0.30"),
        "max_width": Decimal("1.20"),
        "min_height": Decimal("0.70"),
        "max_height": Decimal("0.95"),
        "min_depth": Decimal("0.45"),
        "max_depth": Decimal("0.70"),
        "can_place_on_wall": True,
        "requires_wall": True,
    },
    {
        "name": "Base Cabinet 90cm",
        "description": "Wide base cabinet for kitchen countertops",
        "object_type": "base_cabinet",
        "glb_file": "furniture_objects/base_cabinet_90.glb",
        "default_width": Decimal("0.90"),
        "default_height": Decimal("0.85"),
        "default_depth": Decimal("0.60"),
        "min_width": Decimal("0.60"),
        "max_width": Decimal("1.50"),
        "min_height": Decimal("0.70"),
        "max_height": Decimal("0.95"),
        "min_depth": Decimal("0.45"),
        "max_depth": Decimal("0.70"),
        "can_place_on_wall": True,
        "requires_wall": True,
    },
    {
        "name": "Wall Cabinet 60cm",
        "description": "Wall-mounted cabinet for upper storage",
        "object_type": "wall_cabinet",
        "glb_file": "furniture_objects/wall_cabinet_60.glb",
        "default_width": Decimal("0.60"),
        "default_height": Decimal("0.70"),
        "default_depth": Decimal("0.35"),
        "min_width": Decimal("0.30"),
        "max_width": Decimal("1.20"),
        "min_height": Decimal("0.50"),
        "max_height": Decimal("0.90"),
        "min_depth": Decimal("0.30"),
        "max_depth": Decimal("0.40"),
        "can_place_on_wall": True,
        "requires_wall": True,
    },
    {
        "name": "Refrigerator Standard",
        "description": "Standard size refrigerator",
        "object_type": "refrigerator",
        "glb_file": "furniture_objects/refrigerator.glb",
        "default_width": Decimal("0.70"),
        "default_height": Decimal("1.80"),
        "default_depth": Decimal("0.70"),
        "min_width": Decimal("0.60"),
        "max_width": Decimal("0.90"),
        "min_height": Decimal("1.60"),
        "max_height": Decimal("2.00"),
        "min_depth": Decimal("0.60"),
        "max_depth": Decimal("0.80"),
        "can_place_on_wall": True,
        "requires_wall": False,
    },
    {
        "name": "Oven Range 60cm",
        "description": "Standard oven and cooktop combination",
        "object_type": "oven",
        "glb_file": "furniture_objects/oven_60.glb",
        "default_width": Decimal("0.60"),
        "default_height": Decimal("0.85"),
        "default_depth": Decimal("0.60"),
        "min_width": Decimal("0.50"),
        "max_width": Decimal("0.90"),
        "min_height": Decimal("0.85"),
        "max_height": Decimal("0.90"),
        "min_depth": Decimal("0.55"),
        "max_depth": Decimal("0.70"),
        "can_place_on_wall": True,
        "requires_wall": False,
    },
    {
        "name": "Dishwasher 60cm",
        "description": "Built-in dishwasher",
        "object_type": "dishwasher",
        "glb_file": "furniture_objects/dishwasher_60.glb",
        "default_width": Decimal("0.60"),
        "default_height": Decimal("0.85"),
        "default_depth": Decimal("0.60"),
        "min_width": Decimal("0.45"),
        "max_width": Decimal("0.60"),
        "min_height": Decimal("0.80"),
        "max_height": Decimal("0.90"),
        "min_depth": Decimal("0.55"),
        "max_depth": Decimal("0.65"),
        "can_place_on_wall": True,
        "requires_wall": False,
    },
    {
        "name": "Kitchen Sink Single",
        "description": "Single basin kitchen sink",
        "object_type": "sink",
        "glb_file": "furniture_objects/sink_single.glb",
        "default_width": Decimal("0.80"),
        "default_height": Decimal("0.20"),
        "default_depth": Decimal("0.50"),
        "min_width": Decimal("0.50"),
        "max_width": Decimal("1.00"),
        "min_height": Decimal("0.15"),
        "max_height": Decimal("0.25"),
        "min_depth": Decimal("0.40"),
        "max_depth": Decimal("0.60"),
        "can_place_on_wall": True,
        "requires_wall": False,
    },
    {
        "name": "Kitchen Island 120cm",
        "description": "Freestanding kitchen island with storage",
        "object_type": "island",
        "glb_file": "furniture_objects/island_120.glb",
        "default_width": Decimal("1.20"),
        "default_height": Decimal("0.90"),
        "default_depth": Decimal("0.80"),
        "min_width": Decimal("0.90"),
        "max_width": Decimal("2.00"),
        "min_height": Decimal("0.85"),
        "max_height": Decimal("1.10"),
        "min_depth": Decimal("0.60"),
        "max_depth": Decimal("1.20"),
        "can_place_on_wall": False,
        "requires_wall": False,
    },
    {
        "name": "Tall Pantry Cabinet",
        "description": "Floor-to-ceiling pantry storage",
        "object_type": "tall_cabinet",
        "glb_file": "furniture_objects/tall_cabinet.glb",
        "default_width": Decimal("0.60"),
        "default_height": Decimal("2.20"),
        "default_depth": Decimal("0.60"),
        "min_width": Decimal("0.40"),
        "max_width": Decimal("0.90"),
        "min_height": Decimal("2.00"),
        "max_height": Decimal("2.40"),
        "min_depth": Decimal("0.45"),
        "max_depth": Decimal("0.70"),
        "can_place_on_wall": True,
        "requires_wall": True,
    },
    {
        "name": "Dining Table 150cm",
        "description": "Standard dining table",
        "object_type": "table",
        "glb_file": "furniture_objects/table_150.glb",
        "default_width": Decimal("1.50"),
        "default_height": Decimal("0.75"),
        "default_depth": Decimal("0.90"),
        "min_width": Decimal("1.00"),
        "max_width": Decimal("2.50"),
        "min_height": Decimal("0.70"),
        "max_height": Decimal("0.80"),
        "min_depth": Decimal("0.70"),
        "max_depth": Decimal("1.20"),
        "can_place_on_wall": False,
        "requires_wall": False,
    },
    {
        "name": "Dining Chair",
        "description": "Standard dining chair",
        "object_type": "chair",
        "glb_file": "furniture_objects/chair.glb",
        "default_width": Decimal("0.45"),
        "default_height": Decimal("0.90"),
        "default_depth": Decimal("0.50"),
        "min_width": Decimal("0.40"),
        "max_width": Decimal("0.60"),
        "min_height": Decimal("0.80"),
        "max_height": Decimal("1.10"),
        "min_depth": Decimal("0.45"),
        "max_depth": Decimal("0.60"),
        "can_place_on_wall": False,
        "requires_wall": False,
    },
]

print("Creating furniture objects...")
for data in furniture_data:
    obj = FurnitureObject.objects.create(**data)
    print(f"  ✓ Created: {obj.name}")

print(f"\nCreated {FurnitureObject.objects.count()} furniture objects")

# Create global designer settings
print("\nCreating global designer settings...")
settings = DesignerSettings.objects.create(
    user=None,
    max_placement_depth_from_wall=Decimal("0.80"),
    grid_snap_size=Decimal("0.10"),
    default_object_spacing=Decimal("0.05"),
    allow_object_overlap=False,
    show_placement_guides=True,
    enable_snap_to_grid=True,
    enable_snap_to_wall=True,
    auto_save_interval=30,
)
print(f"  ✓ Created global settings")

print("\n✅ Sample data created successfully!")
