# Generated by Django 5.1.3 on 2025-11-05 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Kitchen', max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length dimension (Y-axis)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width dimension (X-axis)', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height dimension (Z-axis)', max_digits=10)),
                ('wall_thickness', models.DecimalField(decimal_places=2, default=1.0, help_text='Wall thickness for future use', max_digits=10)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='kitchen_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('door', 'Door'), ('window', 'Window'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, help_text="Description for 'other' type objects", max_length=255)),
                ('wall', models.CharField(choices=[('width_wall_1', 'Width Wall 1 (Front)'), ('width_wall_2', 'Width Wall 2 (Back)'), ('length_wall_1', 'Length Wall 1 (Left)'), ('length_wall_2', 'Length Wall 2 (Right)')], help_text='Which wall the object is placed on', max_length=20)),
                ('distance_from_wall_start', models.DecimalField(decimal_places=2, help_text="Distance from wall's begin point to object's begin point", max_digits=10)),
                ('object_width', models.DecimalField(decimal_places=2, help_text='Width of the object along the wall', max_digits=10)),
                ('height_from_ground', models.DecimalField(decimal_places=2, help_text="Distance from ground (0) to object's bottom edge", max_digits=10)),
                ('object_height', models.DecimalField(decimal_places=2, help_text='Height of the object', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='kitchen.kitchen')),
            ],
            options={
                'verbose_name': 'Kitchen Object',
                'verbose_name_plural': 'Kitchen Objects',
                'ordering': ['kitchen', 'wall', 'distance_from_wall_start'],
            },
        ),
    ]
