# Generated by Django 5.1.3 on 2025-11-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='wall_thickness',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Wall thickness', max_digits=10),
        ),
    ]
