# Generated by Django 5.1.2 on 2025-11-24 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_kitchen_wall_thickness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the furniture object', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the object')),
                ('object_type', models.CharField(choices=[('base_cabinet', 'Base Cabinet'), ('wall_cabinet', 'Wall Cabinet'), ('tall_cabinet', 'Tall Cabinet'), ('island', 'Kitchen Island'), ('refrigerator', 'Refrigerator'), ('oven', 'Oven/Range'), ('dishwasher', 'Dishwasher'), ('sink', 'Sink'), ('countertop', 'Countertop'), ('table', 'Table'), ('chair', 'Chair'), ('shelf', 'Shelf'), ('other', 'Other')], help_text='Type/category of the furniture', max_length=30)),
                ('glb_file', models.FileField(help_text='GLB 3D model file', upload_to='furniture_objects/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail preview image', null=True, upload_to='furniture_thumbnails/')),
                ('default_width', models.DecimalField(decimal_places=2, help_text='Default width in meters', max_digits=10)),
                ('default_height', models.DecimalField(decimal_places=2, help_text='Default height in meters', max_digits=10)),
                ('default_depth', models.DecimalField(decimal_places=2, help_text='Default depth in meters', max_digits=10)),
                ('min_width', models.DecimalField(decimal_places=2, help_text='Minimum allowed width', max_digits=10)),
                ('max_width', models.DecimalField(decimal_places=2, help_text='Maximum allowed width', max_digits=10)),
                ('min_height', models.DecimalField(decimal_places=2, help_text='Minimum allowed height', max_digits=10)),
                ('max_height', models.DecimalField(decimal_places=2, help_text='Maximum allowed height', max_digits=10)),
                ('min_depth', models.DecimalField(decimal_places=2, help_text='Minimum allowed depth', max_digits=10)),
                ('max_depth', models.DecimalField(decimal_places=2, help_text='Maximum allowed depth', max_digits=10)),
                ('can_place_on_wall', models.BooleanField(default=False, help_text='Whether this object can be placed against walls (e.g., cabinets)')),
                ('requires_wall', models.BooleanField(default=False, help_text='Whether this object must be placed against a wall')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this object is available in the catalog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Furniture Object',
                'verbose_name_plural': 'Furniture Objects',
                'ordering': ['object_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_placement_depth_from_wall', models.DecimalField(decimal_places=2, default=0.8, help_text='Maximum depth allowed from wall for wall-mounted objects (in meters)', max_digits=10)),
                ('grid_snap_size', models.DecimalField(decimal_places=2, default=0.1, help_text='Grid snap size in meters (0 = no snap)', max_digits=10)),
                ('default_object_spacing', models.DecimalField(decimal_places=2, default=0.05, help_text='Minimum spacing between objects in meters', max_digits=10)),
                ('allow_object_overlap', models.BooleanField(default=False, help_text='Whether objects can overlap each other')),
                ('show_placement_guides', models.BooleanField(default=True, help_text='Show visual guides for valid placement areas')),
                ('enable_snap_to_grid', models.BooleanField(default=True, help_text='Enable snap-to-grid when placing objects')),
                ('enable_snap_to_wall', models.BooleanField(default=True, help_text='Enable automatic snap to walls for wall objects')),
                ('auto_save_interval', models.IntegerField(default=30, help_text='Auto-save interval in seconds (0 = disabled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='User-specific settings (null for global defaults)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designer Settings',
                'verbose_name_plural': 'Designer Settings',
            },
        ),
        migrations.CreateModel(
            name='PlacedFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.DecimalField(decimal_places=2, help_text='X coordinate (0 = left edge of kitchen)', max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=2, help_text='Y coordinate (0 = front edge of kitchen)', max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=2, default=0.0, help_text='Z coordinate (0 = floor level)', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Custom width in meters', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Custom height in meters', max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Custom depth in meters', max_digits=10)),
                ('rotation_angle', models.IntegerField(choices=[(0, '0° (Original)'), (90, '90° (Rotated Right)'), (180, '180° (Rotated 180)'), (270, '270° (Rotated Left)')], default=0, help_text='Rotation in 90-degree increments')),
                ('is_placed_on_wall', models.BooleanField(default=False, help_text='Whether this object is placed against a wall')),
                ('wall_side', models.CharField(choices=[('none', 'None (Free-standing)'), ('front', 'Front Wall (Y=0)'), ('back', 'Back Wall (Y=length)'), ('left', 'Left Wall (X=0)'), ('right', 'Right Wall (X=width)')], default='none', help_text='Which wall side the object is placed against', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('furniture_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='kitchen.furnitureobject')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_furniture', to='kitchen.kitchen')),
            ],
            options={
                'verbose_name': 'Placed Furniture',
                'verbose_name_plural': 'Placed Furniture',
                'ordering': ['kitchen', 'created_at'],
            },
        ),
    ]
