# Generated by Django 5.1.2 on 2025-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_furnitureobject_designersettings_placedfurniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designersettings',
            name='default_object_spacing',
            field=models.DecimalField(decimal_places=3, default=0.005, help_text='Minimum spacing between objects in meters', max_digits=10),
        ),
    ]
